#!/bin/sh
cat >> .env<< EOF
REDIS_URL=${REDIS_URL:-redis://127.0.0.1:6379}
DATABASE_URL=${DATABASE_URL:-postgresql://postgres:123456@127.0.0.1:5432/ai}
DIRECT_URL=${DATABASE_URL:-postgresql://postgres:123456@127.0.0.1:5432/ai}
POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING:-postgresql://postgres:123456@127.0.0.1:5432/ai}
NEXTAUTH_SECRET=aaaaaaa
#OSS
OSS_REGION=${OSS_REGION}
OSS_ACCESS_KEY_ID=${OSS_REGION}
OSS_ACCESS_KEY_SECRET=${OSS_REGION}
OSS_BUCKET=${OSS_REGION}
EOF

PGPASSWORD="${POSTGRES_PASSWORD}" psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}   -h postgres -c "CREATE EXTENSION IF NOT EXISTS vector;"
PGPASSWORD="${POSTGRES_PASSWORD}" psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}  -h postgres -f ./prisma/add-users.sql

echo "start server..."
npm run start
